#!/usr/bin/perl -w

############################################
#hack perronson  pa' cambiar nombres con espacios
#ver 0.0.0.1
#cHeKo @ may-2002 sdelacruz_ower@yahoo.com
############################################

system ('ls *.mp3 > lista_mp3');
open (ENTRADA, "<lista_mp3");
@lista_files = <ENTRADA>;
foreach $file (@lista_files)
{
        $file_new=$file;
        $file_new=~s/\s/_/g;
        $/=_;
        chomp $file_new;
        $/="\n";
        chomp $file;
        system "mv",$file,$file_new;
        print ("nombre antiguo : " . "$file\n");
        print ("nombre nuevo : " . "$file_new\n");
        print("**********************************************************************************************************\n");
        }
print "\n";
close (ENTRADA);
$num_files=@lista_files;
system ('rm -f lista_mp3');
print ("Se han cambiado  " .  "$num_files" . "  archivos\n");
print ("p.d. : ==> Fuck M\$hiT\n" );





