#!/bin/sh
#date +%m%d%k%M%Y"."%S > /tmp/fecha
#mes dia hora minutos año.segundos
#fecha válida de vmware
date 101419142002.00
vmware -x -q /vmware/win98/win98.cfg &
# si tu máquina necesita más tiempo para arrancar vmware, ponle más tiempo a sleep
sleep 7
#acentos agudos, que en netscape no se ven muy bien
#date `cat /tmp/fecha` 
#rm -f /tmp/fecha
ntpdate -u time.nist.gov 2>&1 > /dev/null
