#!/bin/ksh

 
clear
#########################################################################
#   
#          Alumno: Adriana Careaga Hernadez
#          Numcta: 9002613
#          Programacion de sistemas
#          Profesor: Angel Salinas Cervantes
#
########################################################################

echo "\t|#####################################################################|"
echo "\t|==                                                                 ==|"
echo "\t|                    Programacion de sistemas                         |"
echo "\t|=====================================================================|"
echo "\t|                          Menu principal:                            |"
echo "\t|                                                                     |"
echo "\t|                1) Instrucciones                                     |"
echo "\t|                2) Matar procesos                                    |"
echo "\t|                3) Salir al sistema operativo                        |"
echo "\t|                                                                     |"
echo "\t|---------------------------------------------------------------------|"
echo "\t|                                                                     |"
echo "\t|#####################################################################|"
echo "\t|  Eliga una opcion y despues pulse <ENTER> : \c "
read opcion

case $opcion in
	1*) clear
            echo "\t|####################################################################|"
            echo "\t|                                                                    |"
            echo "\t|      Programa realizado por Adriana Careaga Hernandez              |"
            echo "\t|                                                                    |"
            echo "\t|      Numcta: 9002613                                               |"
            echo "\t|      Programacion de sistemas                                      |"
            echo "\t|      Profesor: Angel Salinas                                       |"
            echo "\t|                                                                    |"
            echo "\t| Este programa es para poder localizar y matar procesos deacuerdo   |"
            echo "\t| al identificador de procesos.                                      |"
            echo "\t| Al teclear la opcion 2 del menu principal se mostrara la lista de  |"
            echo "\t| procesos del usuario, y asi seleccionar el proceso o los procesos  |"
            echo "\t| que desea interrumpir.                                             |"
            echo "\t| La opcion 3 es para detener el programa y salir.                   |"
            echo "\t|                                                                    |"
            echo "\t|                                                                    |"
            echo "\t|####################################################################|" 
            echo "\t| pulse "q" para salir o "r" para regresar:\c  "
            read c
                        case $c in
                              [Qq]) exit 2;;
                              [Rr]) ;;
                        esac
             


             ;;
	2*) 
                     clear
                     echo "\t|############################################################|"
                     echo "\t| Los numeros de los procesos son:                           |"
                     ps -efa | grep `whoami` | awk '{ print "   " $2  }'
                     echo "Seleccione el numero de proceso a eliminar: \c"
                     read procesoamorir
                                       ps -efa | grep `whoami` | awk '$2 == $procesoamorir' 
                                       kill -9 $procesoamorir
                                       echo "Pulse <enter> para continuar... "
                     read tecla
                           
        ;;
	3*) clear
            echo "\tsaliendo a AIX...."
            date
            echo "\tGracias  \c" 
            whoami
            echo "\n"
            exit 2 ;;
       *) echo "\t\t Opcion no valida." ;; 
    esac

