#!/bin/sh
# #####################################################
# Programa realizado por Veronica Medina Granados
#                 y   Virginia Hernandez lagrade

until $opcion = 3 
do
clear
echo "|-----------------------------------------|"
echo "|                                         |"
echo "|    Menu de opciones:                    |"
echo "|                                         |"
echo "|     1)   Acerca de....                  |"
echo "|     2)   Programa                       |"
echo "|     3)   Salir del programa             |"
echo "|                                         |"
echo "|    Teclee su opcion:                    |\c"
read opcion
case $opcion in
1) clear
  echo "|----------------------------------------------|"
  echo "|                                        	|"
  echo "|   Acerca de ...................              |"
  echo "|                                              |"
  echo "|   Programa para ver el contenido de          |"
  echo "|   directorios y subdirectorios.              |"
  echo "|                                              |"
  echo "| Programado por: Veronica Medina Granados     |"
  echo "|                 Virginia Hernandez lagarde   |"
  echo "|                                              |"
  echo "|                                              |"
  echo "| Profesor: Angel Salinas                      |"
  echo "| Materia: Programacion avanzada de sistemas   |"
  echo "|                                              |"
  echo "|----------------------------------------------|"
  echo "|  Pulse < ENTER > para regresar al menu       |"
  read resp
	 ;;
2) 
  clear
  echo "|------------------------------------------------|"
  echo "|                                                |"
  echo "| Programa para obtener el numero de directorios |"
  echo "| y el numero de archivos de un subdirectorio.   |"
  echo "|                                                |"
 echo "|  Teclee la ruta:	                            |"
 read ruta
 echo
 echo
 echo "El directorio  '$ruta' tiene" 

 echo "`ls -F $ruta | grep '/$' | wc -l` directorios y "   
 echo "`ls -F $ruta | grep '*$' | wc -l` archivos"  
 echo
 echo 
 echo " Presione <Enter> para regresar al menu. "
 read regresar
 ;;
3)  exit ;;
*) echo fuera ;;
esac
done # aqui se termina el shell

